### ISSUE TITLE
TabView ScrollView bug

### ISSUE THREAD

**Issue by iltyty** [gwentey/2023-perso-learnIO-swift#1]
Hello gwentey, I wonder if you have found a solution to this bug: https://forums.developer.apple.com/forums/thread/730167

**Comment by gwentey** [comment]
Hello iltyty. I didn't i'm sorry :(

**Comment by iltyty** [comment]
oh, sorry to hear that, so what't your workaround or alternative? I run into the same problem and don't know how to fix it. 😩

**Comment by gwentey** [comment]
My solution? I abandoned the Swift because of its ahahahh... Good luck, and if you found a solution tell me

**Comment by iltyty** [comment]
ahaha ok then, I'll see if I can find one. Thank you anyway!
